### ISSUE TITLE
Files needed to run the examples

### ISSUE THREAD

**Issue by joseFranciscoDiez** [DSPsleeporg/smiles-transformer#1]
Thank you very much for all this work. Is really amazing.

I was trying to run the examples and it seems that it is necessary to have some files.

How can you get the following files:

- trfm_12_23000.pkl
- seq2seq_1.pkl
- ep00_it010000.pkl

**Comment by shionhonda** [comment]
Thanks for reading our paper!
For `trfm_12_23000.pkl`, you can download `trfm.pkl` from [Drive](https://drive.google.com/drive/folders/1mY03ZwfaYx7p9AtPPhFtU_TubuBEnxRh).
For `seq2seq_1.pkl`, please run `pretrain_rnn.py`.
The last one is no longer supported because it was just created when I explored some ideas.
Sorry for misconfigurations.

**Comment by xuzhang5788** [comment]
I used downloaded files in examples #1, but I got the following error messages:

RuntimeError                              Traceback (most recent call last)
<ipython-input-13-82a70639659f> in <module>
     17 trfm = TrfmSeq2seq(len(vocab), 256, len(vocab), 3)
     18 #trfm.load_state_dict(torch.load('.save/trfm_12_23000.pkl', map_location=torch.device('cpu')))
---> 19 trfm.load_state_dict(torch.load('../data/trfm.pkl', map_location=torch.device('cpu')))
     20 trfm.eval()
     21 print('Total parameters:', sum(p.numel() for p in trfm.parameters()))

~/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
    837         if len(error_msgs) > 0:
    838             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
--> 839                                self.__class__.__name__, "\n\t".join(error_msgs)))
    840         return _IncompatibleKeys(missing_keys, unexpected_keys)
    841 

RuntimeError: Error(s) in loading state_dict for TrfmSeq2seq:
	Unexpected key(s) in state_dict: "trfm.encoder.layers.3.self_attn.in_proj_weight", "trfm.encoder.layers.3.self_attn.in_proj_bias", "trfm.encoder.layers.3.self_attn.out_proj.weight", "trfm.encoder.layers.3.self_attn.out_proj.bias", "trfm.encoder.layers.3.linear1.weight", "trfm.encoder.layers.3.linear1.bias", "trfm.encoder.layers.3.linear2.weight", "trfm.encoder.layers.3.linear2.bias", "trfm.encoder.layers.3.norm1.weight", "trfm.encoder.layers.3.norm1.bias", "trfm.encoder.layers.3.norm2.weight", "trfm.encoder.layers.3.norm2.bias", "trfm.decoder.layers.3.self_attn.in_proj_weight", "trfm.decoder.layers.3.self_attn.in_proj_bias", "trfm.decoder.layers.3.self_attn.out_proj.weight", "trfm.decoder.layers.3.self_attn.out_proj.bias", "trfm.decoder.layers.3.multihead_attn.in_proj_weight", "trfm.decoder.layers.3.multihead_attn.in_proj_bias", "trfm.decoder.layers.3.multihead_attn.out_proj.weight", "trfm.decoder.layers.3.multihead_attn.out_proj.bias", "trfm.decoder.layers.3.linear1.weight", "trfm.decoder.layers.3.linear1.bias", "trfm.decoder.layers.3.linear2.weight", "trfm.decoder.layers.3.linear2.bias", "trfm.decoder.layers.3.norm1.weight", "trfm.decoder.layers.3.norm1.bias", "trfm.decoder.layers.3.norm2.weight", "trfm.decoder.layers.3.norm2.bias", "trfm.decoder.layers.3.norm3.weight", "trfm.decoder.layers.3.norm3.bias".

**Comment by xuzhang5788** [comment]
My question is different from my issue called "Where is your data folder"
My problem is when I used downloaded files to substitute the files in example #1, I got above error messages.  See this
#trfm.load_state_dict(torch.load('**.save/trfm_12_23000.pkl**', map_location=torch.device('cpu')))
---> 19 trfm.load_state_dict(torch.load('**../data/trfm.pkl**', map_location=torch.device('cpu')))

Many thanks

**Comment by shionhonda** [comment]
Does this solve the problem?
https://github.com/DSPsleeporg/smiles-transformer/issues/5#issuecomment-623955640

**Comment by xuzhang5788** [comment]
@shionhonda 
Thank you. Yes, It solved my problem.
