### ISSUE TITLE
Missing vocab.pkl for pretrained model

### ISSUE THREAD

**Issue by jeremyadamsfisher** [DSPsleeporg/smiles-transformer#11]
I would like to use the pre-trained model but, unless I have misunderstood, I cannot do so without the corresponding `data/vocab.pkl`

In the `ablation_1.ipynb`, you have:
```python
x_split = [split(sm) for sm in df_train['smiles'].values]
xid, _ = get_array(x_split)
X = trfm.encode(torch.t(xid))
```

This relies on the `get_array` function, that refers to the `vocab` defined globally
```python
def get_inputs(sm):
    seq_len = 220
    sm = sm.split()
    if len(sm)>218:
        print('SMILES is too long ({:d})'.format(len(sm)))
        sm = sm[:109]+sm[-109:]
    ids = [vocab.stoi.get(token, unk_index) for token in sm]   # <- ... here
    ids = [sos_index] + ids + [eos_index]
    seg = [1]*len(ids)
    padding = [pad_index]*(seq_len - len(ids))
    ids.extend(padding), seg.extend(padding)
    return ids, seg

def get_array(smiles):
    x_id, x_seg = [], []
    for sm in smiles:
        a,b = get_inputs(sm)
        x_id.append(a)
        x_seg.append(b)
    return torch.tensor(x_id), torch.tensor(x_seg)
```

But this in unpickled from a file which isnt in the reposity:
`vocab = WordVocab.load_vocab('data/vocab.pkl')`

**Comment by rajathsalegame** [comment]
I second this as well :)

**Comment by shionhonda** [comment]
I'm sorry but I think I lost the vocabulary file. Is it possible to reproduce it by executing this file?
https://github.com/DSPsleeporg/smiles-transformer/blob/master/smiles_transformer/build_vocab.py

**Comment by StijnOudshoorn** [comment]
Same problem here, what dataset should the buid_vocab.py be used on in order to recreate the vocab.pkl?

**Comment by shionhonda** [comment]
I extracted SMILE from [ChEMBL 24](https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/releases/chembl_24_1/).

**Comment by manavsingh415** [comment]
@shionhonda could you upload instructions/code for generating the exact same vocab.pkl from the ChEMBL 24 dataset? Thanks
