### ISSUE TITLE
Is pretrained model available?

### ISSUE THREAD

**Issue by masato-tsutsui** [DSPsleeporg/smiles-transformer#13]
Hi, thank you for your great works. When I tried to use the pretrained model embedded in the top page, I found it was just scaler value. In order to load the pickle file, I used python pickle library, and loaded it as binary data. Is there any way to successfully load the pretrained model?
Thank you.

**Comment by shionhonda** [comment]
Please use `torch.load` to load the model file like:

```python
trfm = TrfmSeq2seq(len(vocab), 256, len(vocab), 3)
trfm.load_state_dict(torch.load('.save/trfm_12_23000.pkl'))
```

**Comment by masato-tsutsui** [comment]
Thank you. I got the pretrained-model weights.
