### ISSUE TITLE
Encoding/embedding used in publication?

### ISSUE THREAD

**Issue by stevendbrown** [DSPsleeporg/smiles-transformer#21]
Hi,

Thanks for making this code available. I have a question about the embedding/encoding used in your associated publication. In `pretrain_trfm.py`, the `TrfmSeq2seq._encode` function produces encodings which are the concatenation of the means, maxs, and 0-index of the last and second-to-last outputs. Is this concatenation the encoding which is used for the t-SNE reductions in Figure 3?

Have you investigated the effect of SMILES randomization on the embedding outputs?

Best regards,
Steve

**Comment by shionhonda** [comment]
Hi, thanks for your interest.

>  Is this concatenation the encoding which is used for the t-SNE reductions in Figure 3?

Yes, that is done in [this notebook](https://github.com/DSPsleeporg/smiles-transformer/blob/master/experiments/ablation_3.ipynb).

> Have you investigated the effect of SMILES randomization on the embedding outputs?

No, I haven't. But that would be worth a try!

Shion

**Comment by stevendbrown** [comment]
This manuscript was an excellent inspiration. Thank you very much for sharing it.
