### ISSUE TITLE
Location of the BERT class referenced in the notebook

### ISSUE THREAD

**Issue by dmmiller612** [DSPsleeporg/smiles-transformer#3]
Hello and thanks for publishing the code of your research. I had a quick question after looking at the notebooks. I am frequently seeing a `from bert import BERT` in the notebooks, but I do not see a corresponding BERT class in the codebase or the specified dependencies. Is this something that you implemented separately or is it pulled from an external library?

Thanks,
Derek

**Comment by shionhonda** [comment]
Hi.
BERT model was initially implemented in the exploration phase but removed after all because it didn't work well (so not presented in the paper). Please just ignore it. Sorry to confuse you.
